Kasuba/partial demo
SoundWorkLabs/alpha-marketplace pull request #13
Opened 2023-10-23 12:53 UTC by kasuba97

rushed-merge
will cleaned up the double fetch

2023-10-23 14:44 UTC, hernanarber approved these changes
Looks Good.

2023-10-26 10:37 UTC, jim4067 requested changes

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +            throw new WalletNotConnectedError();
I think this is the wrong error to throw. Why do we have this check when we have one for `wallet`?

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +        const ix = await sdk.createListing(mint, price).then((ix) => {
I'd prefer if we used `async-await` going forward, but this works

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +        }
Do we need this? The SDK should take care of this

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +        }
I don't think we need this too

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +        }
We are already doing this check above 

```ts
if (!provider && !sdk)
```

2023-10-26 10:37 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +    }
why are we signing here if we've already listed?

2023-10-26 10:37 UTC, jim4067 commented on app/explore/data/tracks.tsx
> +
We shouldn't be doing this here

2023-10-26 14:47 UTC, kasuba97 commented on app/explore/data/tracks.tsx
> +
yes, cleaning 😊

2023-10-26 14:56 UTC, kasuba97 commented on app/components/modals/listingNft.tsx
> +    }
we are calling sign there as it wont execute if not called.
should we put it a useEffect?

2023-10-26 15:25 UTC, kasuba97 commented on app/components/modals/listingNft.tsx
> +    }
i have moved the sign prompt code and placed it in the ``useEffect`` this should be resolved now

2023-10-26 15:52 UTC, jim4067 commented on app/components/modals/listingNft.tsx
> +    }
Ahh I see. 

We need to get rid of most of these checks as they're just redundant.

2023-10-26 17:02 UTC, jim4067 approved these changes
This works. 

let's remove the `console.log`s and merge

2023-10-30 12:16 UTC, jim4067 approved these changes

2023-11-01 10:04 UTC, merged